### ISSUE TITLE
Create an API documentation

### ISSUE THREAD

**Issue by dilshankarunarathne** [dilshankarunarathne/storybook#4]
Need to document our project. As a part of that, we need to start off by documenting the API.
I suggest to use a standard technology like OpenAPI or Swagger.

**Comment by kenudeh** [comment]
Hi, I'll take this issue up. Let me know if it's still open.

**Comment by kenudeh** [comment]
Hello, is this done already?

**Comment by dilshankarunarathne** [comment]
Hello @kenudeh.
Thank you for your request to contribute to this project. Although it is finished now, there are a few open issues. 
If you'd like, please contribute to another issue... ❤️
